apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: mysqlservice
spec:
  imagePullSecrets:
  - name: ecr-secret
  containers:
  - name: mysql-container
    image: 108561850742.dkr.ecr.us-east-1.amazonaws.com/mysql_images:v1.0
    ports:
    - containerPort: 3306
      protocol: TCP
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pw
    - name: MYSQL_DATABASE
      value: employees
