apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-mysqldb
  namespace: mysqlservice
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql 
    spec:
      containers:
      - name: mysqldb-container
        image: 108561850742.dkr.ecr.us-east-1.amazonaws.com/mysql_images:v1.0  
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
        - name: MYSQL_DATABASE
          value: employees  